### ISSUE TITLE
Button save on exercise 2 don't appear

### ISSUE THREAD

**Issue by piferrari** [MicrosoftDocs/mslearn-dotnetmaui-create-user-interface-xaml#1]
The button `Save` don't appear. I have to add the code `Grid.Column="2"` on button `Delete` to make it appear.

```xml
<Button
      Grid.Column="2"
      Text="Delete" 
      WidthRequest="100"
      TextColor="{x:Static Member=notes:SharedResources.FontColor}"
      BackgroundColor="{x:Static Member=notes:SharedResources.BackgroundColor}"
      Clicked="OnDeleteButtonClicked" />
```

Tested on Windows 11 and default Android Emulator.

Maui version 6.0.400
Visual Studio Version 17.3.0 Preview 2.0

Best Regards

PiF

**Comment by Padanian** [comment]
Confirmed, the `Grid.Column="2"` is missing
