### ISSUE TITLE
DEP1000 error

### ISSUE THREAD

**Issue by Macka323** [MicrosoftDocs/mslearn-dotnetmaui-create-user-interface-xaml#3]
Hello, i am trying to run the first example in this repo, but i get this error.

- I have tried to restart my PC
- Open VS with admin privileges

but cant get it to work

This is the error that I get  
`Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1000: Cannot copy file "C:\Users\marti\.nuget\packages\microsoft.windowsappsdk\1.1.3\lib\net5.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll" to layout "C:\Users\marti\Downloads\mslearn-dotnetmaui-create-user-interface-xaml-main-2\mslearn-dotnetmaui-create-user-interface-xaml-main\exercise1\Notes\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll". DirectoryNotFoundException - Could not find a part of the path 'C:\Users\marti\Downloads\mslearn-dotnetmaui-create-user-interface-xaml-main-2\mslearn-dotnetmaui-create-user-interface-xaml-main\exercise1\Notes\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll'. [0x80070003]	Notes			
`
![image](https://user-images.githubusercontent.com/75259519/185763295-f3af36f3-e596-4cd1-bbbd-a4a61dbd67e5.png)

Thanks in advance

**Comment by russell-knight** [comment]
I'm having the exact same issue.The error given is `DirectoryNotFoundException` which is odd as I have verified the source and destination directories are correct. 

I wonder if the problem is due to the fact that it is trying to copy `Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll` from the `net5.0-windows10.0.18362.0` directory to the `net6.0-windows10.0.19041.0` directory? Doesn't .NET MAUI only work on .NET 6? Could that mean that a dll from .NET 5 might not be compatible?

**Comment by russell-knight** [comment]
Ok so after playing around with this some more I've managed to fix it. I had initially cloned the app via downloading the Zip file and extracting it. Instead I tried using the "Open with Visual Studio" option and that allowed me to build and run the app. No idea why this would be the case, but for anyone else experiencing this issue it might be worth trying this fix.

**Comment by Macka323** [comment]
I fixed the issue by moving the example out of the extracted folder into a location with smaller path ex. "C:\Users\user\Downloads\example1"

**Comment by jamesmontemagno** [comment]
I will be adding notes in for this. THanks for the feedback.
